### ISSUE TITLE
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [48, 3, 11, 11], but got 3-dimensional input of size [3, 227, 227] instead

### ISSUE THREAD

**Issue by huiyuan414** [Brain-Bridge-Lab/resmem#1]
I have tried the sample codes:
from resmem import ResMem, transformer

model = ResMem(pretrained=True)

from PIL import Image

img = Image.open('127800.png') # This loads your image into memory
img.convert('RGB')

model.eval()

image_x = transformer(img)

prediction = model(image_x)

but I got the error:
# RuntimeError: Expected 4-dimensional input for 4-dimensional weight [48, 3, 11, 11], but got 3-dimensional input of size [3, 227, 227] instead

I really appreciate your advice.

**Comment by vogab** [comment]
Same issue here...

It seems that the transformer() does not create the correct output.

**Comment by SoyBison** [comment]
Hi guys thanks for taking the time to submit an issue. This is actually expected behavior. The model expects images to be fed to it in a batch, so if you're just feeding it one image at a time, you will need to do:

```
img.view(-1,3,227,227)
```

On the image before it can be fed to the system. 

This was a mistake in the readme and has been rectified, i apologize to everyone for the inconvenience and my long response time. I was not notified about this issue until someone emailed me. I have changed the settings on this repository so that i will be notified immediately by any new issues.
